### ISSUE TITLE
Question about import 'index.css?inline'

### ISSUE THREAD

**Issue by farzadmf** [rezasohrabi/chrome-ext-starter#1]
Hey @rezasohrabi , thank you so much for this repo; I learned/reused a lot of things from here for the extension I'm working on.

I do have one question: in `content/index.tsx`, we're doing `import styles from './index.css?inline'`; however, when I do it, my editor is complaining that it "cannot the module or its declarations", however this does not happen in your code.

I tried comparing my Typescript-related things with yours (`tsconfig` etc), but I'm not sure what's missing on my side.

It's worth saying that `vite` is working fine: picking up the styles, adding them to the shadow root, etc. so, _technically_, it's not an issue, but it bothers me to see the error in my editor.

Tried searching the internet, but I don't seem to be able to find anything related to this `import ...?inline` syntax, which is new to me

**Comment by rezasohrabi** [comment]
Hey @farzadmf, I appreciate your kind words! To help you better, could you provide a reproducible sample of your code? Having that would allow me to dig into the problem and provide a more targeted solution. It would be even better if you could share a CodeSandbox link with your code. This way, I can directly see the environment and quickly diagnose the issue.

Regarding your question about import styles from './index.css?inline', this syntax is specific to [Vite](https://vitejs.dev/guide/assets.html#importing-asset-as-string). When you append ?inline to the CSS file path, Vite converts the index.css module to a string and stores it in styles without importing it into the JavaScript file. This allows us to use the string version of the file to append it to the shadow DOM, while also preventing Vite from importing it as a style tag in the host website's DOM.

**Comment by farzadmf** [comment]
Hey @rezasohrabi , thank you for the reply and sorry for the late reply on my side

> this syntax is specific to Vite ...

That's very interesting; very useful info and thanks for the link. Question: seems like the link you provided (the "import as string" section) is using `?raw` for this purpose; do `raw` and `inline` achieve the same thing?

---

As for an example, I have [a repo](https://github.com/farzadmf/videospeed), which I'm VERY gradually trying to re-write using new technologies (Typescript, Vite, etc).

The file where I'm doing this import is [controls.tsx](https://github.com/farzadmf/videospeed/blob/master/src/content/controls.tsx#L6).

It's probably a bit of mess right now as I'm playing and experimenting with things:
- There are a bunch of Javascript files, which work "as is" (no building required etc.)
- I have added the config files (`tsconfig`, `tailwind`, etc.), and the "new" code is in `src`.

One (of many) questions:
- I have a separate `tailwind` config for the content to disable the pre-flight, since I thought that it would affect the host styles; is my understanding/concern true, or using a shadow DOM would make sure the preflight only affects the content script?

Not sure if the repo is something you can check out

**Comment by farzadmf** [comment]
Hey @rezasohrabi didn't hear from you; I guess you didn't have time or the repo initimidated you 😆 

I was hoping you can answer another question I have (tried the internet for a few hours, but to no success):
- I was wondering if there's a way to use different postcss configuration for different sections of the extension
- Basically, the prefixing is super useful for content, where it might have conflicts with the original elements, but, say, in popup or options page, we can "safely" use tailwind classes without worrying about the conflicts

Do you know if there's a way to do that?

**Comment by rezasohrabi** [comment]
Hey Farzad,

I hope you're doing well! Sorry for the delay in my response. I've taken a look at your repo now.

Firstly, let's address the issue with Vite not detecting inline imports. You'll need to include the client type definition of Vite in your src folder. Simply add the following line:

vite-env.d.ts
```javascript
/// <reference types="vite/client" />
``` 

If you're only using Tailwind CSS and there are no conflicts with the host page's styles, you can import Tailwind CSS directly into your shadow DOM. 

Regarding the usage of Tailwind CSS, you can import Tailwind CSS directly into your shadow DOM. Styles imported into a shadow DOM generally do not affect the styles of the outer DOM, and vice versa. This encapsulation ensures that styles remain isolated within the shadow DOM.

However, there might be a Hot Module Replacement (HMR) issue that you can overcome by using the following code in the development environment of your content script:

index.dev.tsx
```typescript
import React from 'react';
import { createRoot } from 'react-dom/client';

import Content from './Content';

import('./index.css');

const container = document.createElement('div');

// The viteDevId represents the path to the CSS file in development mode
const viteDevId = '/chrome-ext-starter/src/content/index.css';

// Get the style element corresponding to the CSS file
const styleElement = document.querySelector(
  `style[data-vite-dev-id*="${viteDevId}"]`
)!;

// Attach the style element to the shadow root
const shadowRoot = container.attachShadow({ mode: 'open' });
shadowRoot.appendChild(styleElement);

document.body.appendChild(container);

// Render the application inside the shadow root
const root = createRoot(shadowRoot);
root.render(<Content />);
``` 

This approach removes the need for adding a postcss config and should work for you. However, working only with Tailwind without using a UI library might be challenging.

If you want to use Daisy UI in your extension, you'll need to configure it using postcss. Having multiple configs might be challenging, but for consistency, you can use shadow DOM in the root of the popup and options pages as well. This way, you won't need multiple postcss configs.

Let me know if you have any further questions or need assistance with anything else!

**Comment by farzadmf** [comment]
> Simply add the following line

Oh wow, nice! I always thought "what's that useless file in there?" 😆 . Thank you!

I really like the idea of using shadow root everywhere consistently; I'll definitely give that a try (and possibly come back with questions 😛 )

I did make [this change](https://github.com/farzadmf/videospeed/commit/e8611dd507d7206c25671361019495e599816747#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873L21), which seems to properly pickup Daisy UI's colors (consistently in content script UI, options, and popup); not sure if it messes something up that I'm not aware
